# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'rnConnectorStreet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for rnConnectorStreet

	use_frameworks!
	pod 'Fabric'
	pod 'Crashlytics'
    pod 'TwitterKit'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'QBImagePickerController'
    pod 'RSKImageCropper'
    
#	pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"  
#  	pod 'React', :path => '../node_modules/react-native', :subspecs => [
#		'DevSupport',
#		'BatchedBridge',
#		'Core',
#    		'RCTText',
#    		'RCTImage',
#    		'RCTWebSocket',
#    		'RCTNetwork',
#	]
#


#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['SWIFT_VERSION'] = '3.0'
#        end
#    end
#end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'yoga'
            target.build_configurations.each do |config|
                config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
                config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
		if config.name == 'Debug'
                	config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['RCT_DEBUG=1','RCT_DEV=1','RCT_NSASSERT=1']
                  end
            end
        end
    end
end


end
